# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czmK6JOnHLINrj8-VGK6tCEtx_0CcubN
"""

# Google Drive Mounten
from google.colab import drive
drive.mount('/content/drive')

# Laden einer .bin Datei
import numpy as np

def read_kitti_bin(file_path):
    pointcloud = np.fromfile(file_path, dtype=np.float32).reshape(-1,4)
    return pointcloud

pointcloud = read_kitti_bin('/content/drive/MyDrive/AITraining_daten/velodyne/frame_0000.bin')
print(pointcloud.shape)  # (N,4)

# Old
import os
import json
import numpy as np
import open3d as o3d

def load_frame(pcd_path, json_path):
    # PCD laden
    pcd = o3d.io.read_point_cloud(pcd_path)
    points = np.asarray(pcd.points)

    # JSON laden
    with open(json_path, 'r') as f:
        data = json.load(f)

    # Leeres Label-Array initialisieren
    labels = np.array(['unlabeled'] * len(points), dtype=object)

    # Mapping: indices -> label
    for figure in data.get("figures", []):
        indices = figure["geometry"]["indices"]
        label = figure.get("geometryType", "unlabeled")
        # Falls du lieber den Klassentitel willst:
        # label = figure.get("classTitle", "unlabeled")
        labels[indices] = label

    return points, labels

def load_dataset(dataset_dir):
    pcd_dir = os.path.join(dataset_dir, "pcd")
    json_dir = os.path.join(dataset_dir, "json")

    frames = []
    pcd_files = sorted([f for f in os.listdir(pcd_dir) if f.endswith(".pcd")])

    for pcd_file in pcd_files:
        name = os.path.splitext(pcd_file)[0]
        pcd_path = os.path.join(pcd_dir, pcd_file)
        json_path = os.path.join(json_dir, f"{name}.json")

        points, labels = load_frame(pcd_path, json_path)

        frame = {
            "name": name,
            "points": points,
            "labels": labels
        }
        frames.append(frame)

    return frames

# Old
from google.colab import drive

dataset_dir = "/content/drive/MyDrive/AITraining_daten/supervisely_raw"

dataset = load_dataset(dataset_dir)

print(f"Frames geladen: {len(dataset)}")

# Erstes Frame inspizieren
frame0 = dataset[0]
print(f"Beispiel Frame Name: {frame0['name']}")
print(f"Punkte Shape: {frame0['points'].shape}")
print(f"Labels Shape: {frame0['labels'].shape}")
print(f"Einzigartige Labels: {np.unique(frame0['labels'])}")

# Punkte mit Label "point_cloud"
mask_person = frame0["labels"] == "point_cloud"
points_person = frame0["points"][mask_person]

print("Anzahl Punkte mit Label 'point_cloud':", len(points_person))

# 1. Dataset Import & Split

import os
import json
import torch
from torch.utils.data import Dataset, DataLoader, random_split
import open3d as o3d
import numpy as np

class PointCloudDataset(Dataset):
    def __init__(self, pcd_dir, json_dir):
        self.pcd_paths = []
        self.label_paths = []
        for fname in sorted(os.listdir(pcd_dir)):
            if fname.endswith(".pcd"):
                frame_name = os.path.splitext(fname)[0]
                self.pcd_paths.append(os.path.join(pcd_dir, fname))
                self.label_paths.append(os.path.join(json_dir, frame_name + ".json"))

    def __len__(self):
        return len(self.pcd_paths)

    def __getitem__(self, idx):
        # Pointcloud laden
        pcd = o3d.io.read_point_cloud(self.pcd_paths[idx])
        points = np.asarray(pcd.points)

        # Labels laden
        with open(self.label_paths[idx], "r") as f:
            data = json.load(f)

        labels = np.zeros(points.shape[0], dtype=np.int64)
        for figure in data.get("figures", []):
            if figure["geometryType"] == "point_cloud":
                indices = figure["geometry"]["indices"]
                labels[indices] = 1  # Mensch = 1, Hintergrund = 0

        return torch.from_numpy(points).float(), torch.from_numpy(labels).long()

# Pfade anpassen
pcd_dir = "/content/drive/MyDrive/AITraining_daten/supervisely_raw/pcd"
json_dir = "/content/drive/MyDrive/AITraining_daten/supervisely_raw/json"

dataset = PointCloudDataset(pcd_dir, json_dir)
print(f"Frames im Dataset: {len(dataset)}")

# Train/Val Split 80/20
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

# 2. DataLoader mit collate_fn zum Padding

from torch.utils.data import DataLoader

def collate_fn(batch):
    points_list = [item[0] for item in batch]
    labels_list = [item[1] for item in batch]

    max_points = max(p.shape[0] for p in points_list)
    batch_size = len(batch)

    padded_points = torch.zeros((batch_size, max_points, 3), dtype=torch.float32)
    padded_labels = torch.zeros((batch_size, max_points), dtype=torch.long)

    for i, (points, labels) in enumerate(zip(points_list, labels_list)):
        length = points.shape[0]
        padded_points[i, :length, :] = points
        padded_labels[i, :length] = labels

    return padded_points, padded_labels

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, collate_fn=collate_fn)
val_loader = DataLoader(val_dataset, batch_size=4, collate_fn=collate_fn)

# 3. Modell: Einfaches PointNet Light

import torch.nn as nn
import torch.nn.functional as F

class SimplePointNet(nn.Module):
    def __init__(self, num_classes=2):
        super(SimplePointNet, self).__init__()
        self.fc1 = nn.Linear(3, 64)
        self.fc2 = nn.Linear(64, 128)
        self.fc3 = nn.Linear(128, 256)
        self.fc4 = nn.Linear(256, 128)
        self.fc5 = nn.Linear(128, num_classes)

    def forward(self, x):
        # x: [B, N, 3]
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = self.fc5(x)  # Output: [B, N, num_classes]
        return x

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = SimplePointNet().to(device)

# 4. Training & Validation Loop

import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

def train_epoch(loader):
    model.train()
    total_loss = 0
    for points, labels in loader:
        points = points.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = model(points)             # [B, N, 2]
        outputs = outputs.permute(0, 2, 1) # [B, 2, N] für CrossEntropyLoss
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

def validate(loader):
    model.eval()
    total_loss = 0
    with torch.no_grad():
        for points, labels in loader:
            points = points.to(device)
            labels = labels.to(device)
            outputs = model(points)
            outputs = outputs.permute(0, 2, 1)
            loss = criterion(outputs, labels)
            total_loss += loss.item()
    return total_loss / len(loader)

num_epochs = 20
for epoch in range(num_epochs):
    train_loss = train_epoch(train_loader)
    val_loss = validate(val_loader)
    print(f"Epoch {epoch+1}/{num_epochs} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f}")

import torch
import plotly.graph_objs as go

# Frame und Modell annehmen, device berücksichtigen
def visualize_frame_with_model(dataset, model, frame_idx=0, device='cpu'):
    model.eval()
    points, _ = dataset[frame_idx]   # Punkte und Labels (Labels ignorieren wir hier)
    points = points.to(device).unsqueeze(0)  # [1, N, 3]

    with torch.no_grad():
        outputs = model(points)  # [1, N, num_classes]
        preds = torch.argmax(outputs, dim=2).squeeze(0)  # [N]

    points_np = points.squeeze(0).cpu().numpy()
    preds_np = preds.cpu().numpy()

    # Farben je Label: 0=Hintergrund (grau), 1=Mensch (rot)
    colors = ['grey' if label == 0 else 'red' for label in preds_np]

    fig = go.Figure(data=[go.Scatter3d(
        x=points_np[:,0],
        y=points_np[:,1],
        z=points_np[:,2],
        mode='markers',
        marker=dict(
            size=2,
            color=colors,
            opacity=0.8
        )
    )])

    fig.update_layout(
        title=f"Frame {frame_idx} mit Modellvorhersagen",
        scene=dict(
            xaxis_title='X',
            yaxis_title='Y',
            zaxis_title='Z'
        ),
        margin=dict(l=0, r=0, b=0, t=30)
    )
    fig.show()

# Beispiel: Visualisiere Frame 0
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
visualize_frame_with_model(dataset, model.to(device), frame_idx=0, device=device)

from sklearn.cluster import DBSCAN
import numpy as np

def cluster_and_count_people(points, preds, eps=0.5, min_samples=10):
    """
    Clustert die Punkte, die als Mensch klassifiziert wurden.
    Args:
        points: np.array (N,3) Punktkoordinaten
        preds: np.array (N,) Vorhersagen 0/1
        eps: float, max. Distanz für DBSCAN (anpassen je nach Daten)
        min_samples: int, Mindestpunkte pro Cluster

    Returns:
        cluster_labels: np.array mit Cluster-IDs für Menschen-Punkte (-1 = Rauschen)
        num_people: int, Anzahl gefundener Cluster (ohne Rauschen)
    """
    human_points = points[preds == 1]
    if len(human_points) == 0:
        return np.array([]), 0

    clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(human_points)
    cluster_labels = clustering.labels_
    num_people = len(set(cluster_labels)) - (1 if -1 in cluster_labels else 0)
    return cluster_labels, num_people

# Beispiel: Cluster für Frame 0 ermitteln
frame_idx = 0
points, _ = dataset[frame_idx]
points_np = points.numpy()

model.eval()
with torch.no_grad():
    inputs = points.unsqueeze(0).to(device)
    outputs = model(inputs)
    preds = torch.argmax(outputs, dim=2).squeeze(0).cpu().numpy()

cluster_labels, num_people = cluster_and_count_people(points_np, preds, eps=0.5, min_samples=10)
print(f"Geschätzte Anzahl Personen in Frame {frame_idx}: {num_people}")

import numpy as np
from sklearn.cluster import DBSCAN
import plotly.express as px
import torch

def cluster_and_count_people(points, preds, eps=0.5, min_samples=10):
    human_points = points[preds == 1]
    if len(human_points) == 0:
        return np.array([]), 0, human_points

    clustering = DBSCAN(eps=eps, min_samples=min_samples).fit(human_points)
    cluster_labels = clustering.labels_
    num_people = len(set(cluster_labels)) - (1 if -1 in cluster_labels else 0)
    return cluster_labels, num_people, human_points

def visualize_clusters(points, cluster_labels):
    # -1 sind Ausreißer (Rauschen), färben wir grau
    colors = ['grey' if label == -1 else f'cluster_{label}' for label in cluster_labels]

    fig = px.scatter_3d(
        x=points[:, 0], y=points[:, 1], z=points[:, 2],
        color=colors,
        title="Cluster-Visualisierung der Personenpunkte",
        labels={"color": "Cluster ID"}
    )
    fig.update_traces(marker=dict(size=3))
    fig.show()

# Beispiel mit Frame 0
frame_idx = 0
points, _ = dataset[frame_idx]
points_np = points.numpy()

model.eval()
with torch.no_grad():
    inputs = points.unsqueeze(0).to(device)  # [1, N, 3]
    outputs = model(inputs)
    preds = torch.argmax(outputs, dim=2).squeeze(0).cpu().numpy()

cluster_labels, num_people, human_points = cluster_and_count_people(points_np, preds, eps=0.5, min_samples=10)

print(f"Geschätzte Anzahl Personen in Frame {frame_idx}: {num_people}")

if len(human_points) > 0:
    visualize_clusters(human_points, cluster_labels)
else:
    print("Keine Personenpunkte gefunden zum Clustern.")

# Modell speichern:
save_path = "/content/drive/MyDrive/model.pth"
torch.save(model.state_dict(), save_path)
print(f"Modell gespeichert unter: {save_path}")

!ls /content/drive/MyDrive/AITraining_daten/